# Generated by Django 4.2.21 on 2025-05-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='name',
        ),
        migrations.AddField(
            model_name='entry',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='entry',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='entry',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='program',
            field=models.CharField(choices=[('math', 'Математика'), ('sovbak', 'СовБак')], max_length=10, verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='score',
            field=models.IntegerField(verbose_name='Средний балл'),
        ),
    ]
